#!/usr/bin/env python3
"""从 skills/ 单一事实源生成其他智能体生态的适配文件。

生成物(规则文本带 GENERATED 头,资源与脚本逐字节复制;勿手改):
  adapters/generic/amphoreus-router.md          便携版总路由(含卡索引与关系单源 relations.md 原文)
  adapters/generic/amphoreus-<hero>.md          便携版单卡 = 家族公约 + 卡文原文
  adapters/generic/assets/stickers/            对话表情与清单
  adapters/generic/scripts/stickers.py          标准库选图脚本
  adapters/openai-codex/AGENTS.md               AGENTS.md 约定(Codex / OpenCode / Amp / Jules 等)
  adapters/gemini-cli/GEMINI.md                 Gemini CLI 约定
  adapters/cline/amphoreus.md                   Cline(.clinerules/)/ Roo Code(.roo/rules/)规则文件
  adapters/github-copilot/copilot-instructions.md  GitHub Copilot 仓库自定义指令
  adapters/windsurf/amphoreus.md                Windsurf(Cascade)规则文件
  adapters/aider/CONVENTIONS.md                 Aider 约定文件(--read 加载)
  adapters/trae/project_rules.md                Trae 项目规则
  adapters/qwen-code/QWEN.md                    Qwen Code 约定
  adapters/iflow-cli/IFLOW.md                   iFlow CLI 约定

CI 会重跑本脚本并要求零 diff(适配层不得手改漂移)。
"""
from __future__ import annotations

import argparse
import hashlib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILLS = ROOT / "skills"
ADP = ROOT / "adapters"

HEROES = [
    ("aglaea", "阿格莱雅", "黄金的织者", "织造法:项目规划/排期/取舍/里程碑"),
    ("cerydra", "刻律德菈", "执棋的君主", "立法三读:可评审、可撤销的工程规则"),
    ("terrae", "丹恒", "掣地的伏龙", "承载法:开发环境/CI 构建/依赖底座/可逆迁移"),
    ("phainon", "白厄", "负火的囚徒", "推石法:大型重构与批量迁移"),
    ("anaxa", "那刻夏", "殁世的学士", "五问法+删除测试:代码/设计/论证评审"),
    ("cipher", "赛飞儿", "捷足的羁客", "行窃三则:授权内对抗测试与漏洞报告"),
    ("hyacine", "风堇", "摇光的医师", "双处方:bug 诊断修复与维护债"),
    ("march7th", "三月七/长夜月", "隐秘的陌客", "拍照式记录法+底片法:日志与快照;备份/回滚/脱敏"),
    ("castorice", "遐蝶", "死荫的侍女", "告别四步:API/依赖/项目退役"),
    ("cyrene", "昔涟", "无瑕的真我", "如我所书法:项目记忆/阶段叙事/终版总装"),
    ("mydei", "万敌", "亡国的王储", "先让十步法:硬 bug/瓶颈/死锁突破"),
    ("hysilens", "海瑟音", "奏浪的剑骑", "歌集复盘法+无路引航式:不归罪复盘/取舍导航"),
    ("tribbie", "缇宝", "命运的三子", "三声部讲解法:分受众技术讲解"),
]


def sha16(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest().upper()[:16]


def read(p: Path) -> str:
    return p.read_text(encoding="utf-8")


def add_text(outputs: dict[Path, bytes], p: Path, text: str) -> None:
    outputs[p] = text.encode("utf-8")


def gen_header(*sources: Path) -> str:
    rows = "\n".join(f"     {s.relative_to(ROOT).as_posix()} (sha256:{sha16(s)}…)" for s in sources)
    return (
        "<!-- GENERATED by adapters/build.py — 勿手改,改 skills/ 后重跑脚本。来源:\n"
        f"{rows}\n-->\n\n"
    )


def card_index() -> str:
    lines = ["| 卡 | 角色 | 司职 |", "| --- | --- | --- |"]
    for key, name, title, method in HEROES:
        lines.append(f"| `amphoreus-{key}` | {name}「{title}」 | {method} |")
    return "\n".join(lines)


USAGE_NOTE = (
    "> **用法**:把本文件作为系统提示 / 规则文件加载即可独立使用。"
    "台词库 `skills/amphoreus-<hero>/persona.md` 为可选伴读,工作场仅在 ≤15% 风格预算内取用(陪聊 / 沙龙场不计);"
    "严肃场景(报错、不可逆操作、安全)自动静音,方法照常执行。"
    "陪聊 / 沙龙场规则见文内家族公约〈沙龙与陪聊〉;多角沙龙的称呼与兴趣边以关系单源 relations.md 为准(附于便携版总路由文件)。\n"
    "\n> **表情资源定位**:连同本文件所在 `generic/` 目录的 `assets/stickers/` 与 `scripts/stickers.py` 一起部署。"
    "文内原生 `amphoreus` 根目录在便携版中对应本文件所在的 `generic/` 目录;"
    "`references/stickers.md` 对应本文件末尾内嵌的表情索引。按实际部署路径读取资源并输出图片绝对路径。"
    "无文件工具或仅粘贴系统提示的宿主自然省略图片;仅在用户明确提供并已验证可用时使用其图片地址,不推测远程回退地址。\n"
)


def build_generic(outputs: dict[Path, bytes]) -> None:
    common = SKILLS / "amphoreus" / "references" / "common.md"
    relations = SKILLS / "amphoreus" / "references" / "relations.md"
    router = SKILLS / "amphoreus" / "SKILL.md"
    stickers = SKILLS / "amphoreus" / "references" / "stickers.md"
    sticker_index = (
        "\n---\n\n## 表情索引(skills/amphoreus/references/stickers.md 原文)\n\n"
        + read(stickers)
    )
    add_text(
        outputs,
        ADP / "generic" / "amphoreus-router.md",
        gen_header(router, common, relations, stickers)
        + "# Amphoreus 总路由(便携版)\n\n"
        + USAGE_NOTE
        + "\n## 卡索引\n\n"
        + card_index()
        + "\n\n---\n\n## 路由卡文(skills/amphoreus/SKILL.md 原文)\n\n"
        + read(router)
        + "\n---\n\n## 家族公约(skills/amphoreus/common.md 原文)\n\n"
        + read(common)
        + "\n---\n\n## 关系单源(skills/amphoreus/references/relations.md 原文:称呼矩阵 / 兴趣边 / 同场禁区 / 沙龙参数)\n\n"
        + read(relations)
        + sticker_index,
    )
    for key, name, title, method in HEROES:
        sk = SKILLS / f"amphoreus-{key}" / "SKILL.md"
        add_text(
            outputs,
            ADP / "generic" / f"amphoreus-{key}.md",
            gen_header(sk, common, stickers)
            + f"# {name}「{title}」·便携版单卡\n\n"
            + f"`amphoreus-{key}` —— {method}\n\n"
            + USAGE_NOTE
            + "\n---\n\n## 卡文(SKILL.md 原文)\n\n"
            + read(sk)
            + "\n---\n\n## 家族公约(common.md 原文)\n\n"
            + read(common)
            + sticker_index,
        )


def build_sticker_runtime(outputs: dict[Path, bytes]) -> None:
    native = SKILLS / "amphoreus"
    assets = native / "assets" / "stickers"
    if not (assets / "manifest.json").is_file() or not any(assets.rglob("*.webp")):
        raise ValueError("缺少原生表情清单或 WebP 资源,请先生成 skills/amphoreus/assets/stickers/。")
    for source in sorted(assets.rglob("*")):
        if source.is_file():
            outputs[ADP / "generic" / source.relative_to(native)] = source.read_bytes()
    helper = native / "scripts" / "stickers.py"
    outputs[ADP / "generic" / "scripts" / helper.name] = helper.read_bytes()


CONVENTION_BODY = """# 翁法罗斯 Skill 套件 —— {tool} 适配

本工作区携带「翁法罗斯 Skill 套件」:13 张工程方法卡 + 1 个总路由。每张卡工作时是一套可执行、可验收的工程方法论,闲时是可陪聊、可入沙龙的角色形态;工程任务中只按方法行事,除非用户明确发起闲聊,不主动入戏。

## 调用规则

1. **用户点名某卡**(如「用 amphoreus-mydei 追这个死锁」)→ 读取 `adapters/generic/amphoreus-<hero>.md` 并按其行事;
2. **用户未点名但任务命中某卡司职** → 先读 `adapters/generic/amphoreus-router.md`,按其路由规则选卡,向用户确认后加载;
3. **工作场一次只演一张卡**,不混声,切卡须经用户确认;沙龙(陪聊专用多角形态)例外——逐条「◯◯」冠名、同场活跃 ≤4 人,规则见家族公约〈沙龙与陪聊〉;
4. **用户发起闲聊 / 沙龙**(寒暄、剧情漫谈、点名找角色聊天)→ 单角陪聊直接加载该角色便携卡;多角沙龙读 `adapters/generic/amphoreus-router.md`(内附〈沙龙与陪聊〉与关系单源 relations.md),由总路由主持。

## 卡索引

{index}

## 家族硬规(摘要,全文见各便携卡内附公约)

- 角色风格 ≤ 全部输出的 15%(工作场口径);报错、不可逆操作、安全事项自动静音,只留方法;
- 沙龙(多角群聊)与陪聊(单角闲聊)依家族公约〈沙龙与陪聊〉:逐条「◯◯」冠名不混声、同场活跃 ≤4 人、闲聊免工作模板与逐轮回执;升档三要素(对象+动作+产出)齐即回到工作模板,审计件一件不少;角色互称以便携版总路由内附的 relations.md 为单源;
- 流水线上游产物按「移交事实包」原文传递,不改写、不摘要冒充原文;
- 所需卡未部署时报告 `module_unavailable: amphoreus-<hero>` 并保留事实包,不代演;
- 台词只出自各卡 persona.md(已逐字对齐游戏公开语料),不虚构引文。

## 两条流水线

- **逐火线**(新特性,10 站):aglaea → cerydra → terrae → phainon → anaxa → cipher → hyacine → march7th → castorice → cyrene
- **守夜线**(事故响应,4 站):mydei → hyacine → march7th → hysilens
"""


CONVENTION_TARGETS = [
    # (输出相对路径, 工具名, 安装说明)
    ("openai-codex/AGENTS.md",
     "AGENTS.md 约定(OpenAI Codex / OpenCode / Amp / Jules 等)",
     "把本文件放到项目根(或全局 `~/.codex/AGENTS.md`),并把整个仓库的 `adapters/generic/` 一并携带。"),
    ("gemini-cli/GEMINI.md",
     "Gemini CLI",
     "把本文件放到项目根或 `~/.gemini/GEMINI.md`,并把 `adapters/generic/` 一并携带。"),
    ("cline/amphoreus.md",
     "Cline / Roo Code",
     "Cline 拷入项目 `.clinerules/` 目录;Roo Code 拷入项目 `.roo/rules/` 目录(Roo 不读目录形态的 `.clinerules/`)。两者均把 `adapters/generic/` 一并携带。"),
    ("github-copilot/copilot-instructions.md",
     "GitHub Copilot(仓库自定义指令)",
     "把本文件拷为项目 `.github/copilot-instructions.md`,并把 `adapters/generic/` 一并携带。"),
    ("windsurf/amphoreus.md",
     "Windsurf(Cascade 规则)",
     "把本文件拷入项目 `.windsurf/rules/` 目录,并把 `adapters/generic/` 一并携带。"),
    ("aider/CONVENTIONS.md",
     "Aider(约定文件)",
     "把本文件放到项目根,启动时 `aider --read CONVENTIONS.md` 加载(或写入 `.aider.conf.yml` 的 `read:`),并把 `adapters/generic/` 一并携带。"),
    ("trae/project_rules.md",
     "Trae(项目规则)",
     "把本文件拷为项目 `.trae/rules/project_rules.md`,并把 `adapters/generic/` 一并携带。"),
    ("qwen-code/QWEN.md",
     "Qwen Code",
     "把本文件放到项目根或 `~/.qwen/QWEN.md`,并把 `adapters/generic/` 一并携带。"),
    ("iflow-cli/IFLOW.md",
     "iFlow CLI",
     "把本文件放到项目根或 `~/.iflow/IFLOW.md`,并把 `adapters/generic/` 一并携带。"),
]


def build_conventions(outputs: dict[Path, bytes]) -> None:
    index = card_index()
    src = SKILLS / "amphoreus" / "SKILL.md"
    for rel, tool, install in CONVENTION_TARGETS:
        add_text(
            outputs,
            ADP / Path(rel),
            gen_header(src)
            + CONVENTION_BODY.format(tool=tool, index=index)
            + f"\n> 安装:{install}\n",
        )


def generated_outputs() -> dict[Path, bytes]:
    outputs: dict[Path, bytes] = {}
    build_generic(outputs)
    build_sticker_runtime(outputs)
    build_conventions(outputs)
    return outputs


def stale_assets(outputs: dict[Path, bytes]) -> list[Path]:
    assets = ADP / "generic" / "assets" / "stickers"
    return sorted(p for p in assets.rglob("*") if p.is_file() and p not in outputs)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="只读检查所有生成文件、图片与索引是否同步")
    args = parser.parse_args()
    outputs = generated_outputs()
    stale = stale_assets(outputs)
    if args.check:
        drift = [p for p, data in outputs.items() if not p.is_file() or p.read_bytes() != data]
        for p in drift:
            print(f"out of sync: {p.relative_to(ROOT)}")
        for p in stale:
            print(f"stale asset: {p.relative_to(ROOT)}")
        if drift or stale:
            raise SystemExit(1)
        print(f"adapters in sync: {len(outputs)} files")
        return
    print("generating adapters:")
    for p, data in outputs.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_bytes(data)
        print(f"  {p.relative_to(ROOT)}")
    asset_root = (ADP / "generic" / "assets" / "stickers").resolve()
    for p in stale:
        if not p.resolve().is_relative_to(asset_root):
            raise ValueError(f"生成资源路径越界: {p}")
        p.unlink()
        print(f"  removed stale asset: {p.relative_to(ROOT)}")
    print("done.")


if __name__ == "__main__":
    main()
